import type { Metadata } from "next";
import "./globals.css";
import ProviderRedux from "@/redux/ProviderRedux";



export const metadata: Metadata = {
  title: "Word finder",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.jpeg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">

      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
      </head>

      <body  >
        <ProviderRedux>
          {children}
        </ProviderRedux>
      </body>
    </html>
  );
}
